language: java
install: mvn install clean --fail-never --quiet -DskipTests=true -Dinvoker.skip=true
script: mvn verify

notifications:
  email: christianedwardgruber@gmail.com

branches:
  except:
    - gh-pages
